### ISSUE TITLE
Release with axe-core 3.3.1

### ISSUE THREAD

**Issue by badtant** [dequelabs/react-axe#101]
Hi,

Is it possible to make a release with axe-core dep as 3.3.1?
Would be nice with the new tests.

Thanks

**Comment by straker** [comment]
Sure, let me try to get a release together.

**Comment by straker** [comment]
We have a release scheduled for axe-core 3.3.2 next week, so we're going to wait for that and then we can create a release for react-axe that pulls it in.

**Comment by badtant** [comment]
Any news on that axe-core release?

**Comment by straker** [comment]
Yep, was just released. Will create a pr for the updated version later today
