### ISSUE TITLE
Warnings when used with React.StrictMode

### ISSUE THREAD

**Issue by anthonyhastings** [dequelabs/react-axe#105]
I'm encountering issues when adding `react-axe` into a project that has `React.StrictMode` within it's component tree. The error in particular is:

```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Provider which renders StrictMode children. Instead, add a ref directly to the element you want to reference.
```

Regarding usage of `findDOMNode`:
https://reactjs.org/docs/strict-mode.html#warning-about-deprecated-finddomnode-usage

I noticed that some preliminary work had begun around this issue in https://github.com/dequelabs/react-axe/pull/82 but I didn't see any open issues, and decided to make this one.

**Comment by mconiglio** [comment]
Any news on this? We are facing this issue as well

**Comment by ticklemepierce** [comment]
We are also seeing this, though the extension seems to be working.

**Comment by zvebbo** [comment]
We also have this problem. As ticklemepierce pointed out, the a11y violations are logged but hey are however drowned out by the findDOMNode warnings. 
Any idea on how to solve this?

**Comment by arvigeus** [comment]
Another bump to this thread

**Comment by straker** [comment]
We have moved this package to be under our [axe-core-npm](https://github.com/dequelabs/axe-core-npm/) monorepo for easier management. As a result, this repository will be deprecated in the coming weeks. 

I have [transferred the issue](https://github.com/dequelabs/axe-core-npm/issues/94) so we can still keep track of it.
