### ISSUE TITLE
Provide an option to configure the colors

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/react-axe#112]
In #100, it was pointed out that the contrast is too low on the light theme. Changing this will introduce issues in the dark theme. The only real solution here is to make this configurable. Given that the same project will run on different machines, we should think if there's a way to:

1. Make this configurable in the code base, to establish a default
2. Allow someone to customise this on their machine in a way that is persistent. Maybe by having a method that someone can call that saves a preference in local storage?

**Comment by straker** [comment]
Closing via #142. Testing will be done in #108
