### ISSUE TITLE
input field in iframe stop responding to user interaction on iOS Safari

### ISSUE THREAD

**Issue by liy** [dequelabs/react-axe#113]
react-axe has some kind interference of user interaction on iOS Safari. input field in iframe can't be focus reliably.

Steps to reproduce:

1. With the react-axe enabled and a iframe with input fields presented on the page.
2. Tap the input field in the iframe, it works fine.
3. Tap done of the onscreen keyboard to the hide the keyboard.
4. Tap anything outside of the iframe.
5. Tap the input field in the iframe. The input field will no longer be able to get focus.

The last step might be intermitent. If you keep trying, eventually after 2 or 3 tires it might start working again.

We have tried on several iOS devices, iPhone 6, iPad, iPad Air. They all produce the same issue.

iOS version: 12.3.1
react-axe: 3.2.0
react: 16.9.0
react-dom: 16.9.0

**Comment by straker** [comment]
We have moved this package to be under our [axe-core-npm](https://github.com/dequelabs/axe-core-npm/) monorepo for easier management. As a result, this repository is now deprecated. 

If this issue is still a problem, please feel free to open a ticket in the new repo.
