### ISSUE TITLE
Set sideEffects to help dead code elimination?

### ISSUE THREAD

**Issue by FezVrasta** [dequelabs/react-axe#114]
Given this ES modules code:

```js
import React from 'react';
import ReactDOM from 'react-dom';
import axe from 'react-axe';

if (process.env.NODE_ENV !== 'production') {
  axe(React, ReactDOM, 1000);
}

ReactDOM.render(<div />, document.querySelector('#root'));
```

If the app is built in `production` mode, the `react-axe` package will not get stripped out from the bundle.

If this package defined `sideEffects: false` in its `package.json`, it would help webpack and Terser to dead code eliminate it.

This is needed in projects that don't make use of RequireJS imports, but only use standard ES modules imports.

**Comment by WilcoFiers** [comment]
We recommend using dynamic `import()` as a way to avoid using CommonJS. Although since CommonJS is supported everywhere you can use `sideEffects`, we recommend using `require`, instead of importing a module and having a bundler tree-shake it out.

**Comment by FezVrasta** [comment]
I'm sorry you decided to dismiss this issue so quickly.

For anyone interested in a solution to this problem, I published `react-axe-es` on npm, which is a thin wrapper around `react-axe`, with the `sideEffects` flag set.

https://www.npmjs.com/package/react-axe-es
