### ISSUE TITLE
Error: Expect axe._selectorData to be set up

### ISSUE THREAD

**Issue by benchudev** [dequelabs/react-axe#116]
I intermittently get the following error with react-axe:

`axe.js:5500 Uncaught (in promise) Error: Expect axe._selectorData to be set up
    at generateSelector (axe.js:5500)
    at Object.createUniqueSelector [as getSelector] (axe.js:5556)
    at DqElement.get selector [as selector] (axe.js:4909)
    at axe.js:4340
    at Array.map (<anonymous>)
    at axe.js:4333
    at Array.map (<anonymous>)
    at axe.js:4330
    at Array.forEach (<anonymous>)
    at Object../node_modules/axe-core/axe.js.helpers.processAggregate (axe.js:4322)`

It tends to happen when I have a lot of component updates happening.

using **axe-core 3.3.2**, **react-axe 3.3.0**
implementing as follows in root of my application:

`if (process.env.NODE_ENV !== 'production') {
  const axe = require('react-axe');
  axe(React, ReactDOM, 1000);
}`

I saw a fix had previously been added to solve this: **https://github.com/dequelabs/react-axe/issues/32**

**Comment by dmbrooking** [comment]
I don't know if this is the "right" solution... but I was having the same problem and saw this in the docuementation:

`The third argument to the exported function is the number of milliseconds to wait for component updates to cease before performing an analysis of all the changes. The changes will be batched and analyzed from the closest common ancestor of all the components that changed within the batch. This generally leads to the first analysis for a dynamic application, analyzing the entire page (which is what you want), while subsequent updates will only analyze a portion of the page (which is probably also what you want).`

I changed `1000` to `5000` and it seems to have stopped the error from happening. (I'm guessing this means my root issue is that I have an underperforming core react app issue, but this does seem to get rid of the axe error)

**Comment by chimericdream** [comment]
I am seeing this as well. I saw that a new version of `axe-core` was just published, so I tested with that but still got the error.

Tested with:
 * `axe-core@3.3.2` + `react-axe@3.3.0`
 * `axe-core@3.4.0` + `react-axe@3.3.0`

The error showed up in both cases.

**Comment by tombartlettmh** [comment]
I am also seeing this - I think in part due to a Usabilla script being added to the DOM and an iframe being injected by the 3rd party.

**Comment by padmavemulapati** [comment]
Unable to execute react-axe, because of an update of chrome. Making the tiket work in progress and will verify once issue fixed.

**Comment by padmavemulapati** [comment]
Seeing the debounce (timeout) changes, and not getting any exceptions even after 10 times executed. on latest  react-axe(3.4.1), the debounce fix made it issue fixed. Everything looks good in this context.
