### ISSUE TITLE
TypeError: axe is not a function

### ISSUE THREAD

**Issue by brightpixels** [dequelabs/react-axe#121]
**Describe the bug**
I was trying to follow this guide https://web.dev/accessibility-auditing-react but got this error when I tried to launch the app: `TypeError: axe is not a function`

**To Reproduce**
1. Generate react app using create-react-app (CRA)
2. Replace `ReactDOM.render(<App />, document.getElementById('root'));` with the following
````
if (process.env.NODE_ENV !== 'production') {
  import('react-axe').then(axe => {
    axe(React, ReactDOM, 1000);
    ReactDOM.render(<App />, document.getElementById('root'));
  });
} else {
  ReactDOM.render(<App />, document.getElementById('root'));
}
````

3. `npm start`

** Fix that has worked for me**
`axe.default(React, ReactDOM, 1000);` instead of `axe(React, ReactDOM, 1000);`

**Screenshots**
https://ibb.co/82znTRy

**Comment by straker** [comment]
That seems correct to me. Dynamic imports use the `default` property to use the default export. See https://flaviocopes.com/javascript-dynamic-imports/.
