### ISSUE TITLE
AXE not analyzing changes updated from React-Router

### ISSUE THREAD

**Issue by sudPatil** [dequelabs/react-axe#122]
Hi, 
I am using basic implementation of react to test a11y using axe.
But once same code integrated with react-router, Axe is not analyzing component for a11y errors updated by Router.

App.js
```
axe(React, ReactDOM, 1000);
ReactDOM.render(
    <Provider store={store}>
        <RouterCom />
    </Provider>, document.getElementById('root')
);
````

RouterCom.js

```
<Router history={this.history}>
    <div><Link to='/'>Home</Link></div>
    <div><Link to='/about'>about</Link></div>
    <div><Link to='/profile'>profile</Link></div>
    <Switch>
        <Route exact path='/' render={() => (<div><img src="#" title="home" /></div>)} />
        <Route path='/about' render={() => (<img src="#" />)} />
        <Route path='/profile' component={Profile} />
    </Switch>
</Router>
```

On first load console giving error for alt text, but once clicked on other links( about/profile) its not reporting any issues from current loaded component( about / profile).

On clearing console and clicking on home link not giving original error also.

My assumption is it should give error for all dynamic loaded component if any.
If not can anybody explain how to achieve a11y testing in such scenario.

**Version using**
```
"react": "^16.8.6",
"react-dom": "^16.8.6",
"react-axe": "^3.3.0",
"react-router-dom": "^5.1.2",
```

**Note**
* Same behavior seen for state changes and conditional rendering

**Comment by straker** [comment]
We have moved this package to be under our [axe-core-npm](https://github.com/dequelabs/axe-core-npm/) monorepo for easier management. As a result, this repository will be deprecated in the coming weeks. 

I have [transferred the issue](https://github.com/dequelabs/axe-core-npm/issues/92) so we can still keep track of it.
