### ISSUE TITLE
Reject/ignore issues

### ISSUE THREAD

**Issue by moritzjacobs** [dequelabs/react-axe#123]
Maybe I'm mistaken about how to use react-axe/aXe in general, but: wouldn't it be a nice feature to be able to reject/ignore issues for specific elements in specific components if you really want to? Kind of like a eslint suppression comment.

```
<MyComponent axe-reject={true} />
```
Or is there a way to do this, that I don't see?

Thanks for your help!

**Comment by moritzjacobs** [comment]
FYI, I added the following to our project now:

```ts
const matches = (node: Element) => !(node.getAttribute('data-axe-reject') === 'true');

ReactAxe(React, ReactDOM, 0, {
	rules: [
		{
			id: 'color-contrast',
			matches,
		},
	],
});
```

```tsx
<Wrapper data-axe-reject={true}>
	<InnerElement data-axe-reject={true}>
		<p data-axe-reject={true}>Some text</p>
	</InnerElement>
</Wrapper>
```

… which does the trick but has 2 downsides: 

1. It only works on a rule by rule basis, I can not reject all rules at once (not that big of a deal)
2. In the case of this color-contrast issue, I have to add the `data-axe-reject` property to every element in the tree.

Maybe this can be improved?

**Comment by straker** [comment]
Axe doesn't have a way to ignore issues at the moment, but I'll add it as a feature request for it.

**Comment by straker** [comment]
We have moved this package to be under our [axe-core-npm](https://github.com/dequelabs/axe-core-npm/) monorepo for easier management. As a result, this repository will be deprecated in the coming weeks. 

The root problem is that axe-core does not support ignoring known issues. I'm not sure axe-core will add that capability but please follow axe-core releases for further development.
