### ISSUE TITLE
False positives in dev

### ISSUE THREAD

**Issue by amberleyromo** [dequelabs/react-axe#124]
Would appreciate any help troubleshooting this.

# Description

Using `react-axe` in a Gatsby project. It's throwing errors where I've confirmed it shouldn't. 

I was thinking it could be a hydration/timing issue, but the dropdown with further info confirms the elements are there (in this case, `<title>` element and `lang` attr on `<html>`

# Console output

<img width="1062" alt="Screen Shot 2019-11-26 at 11 46 47 AM" src="https://user-images.githubusercontent.com/3461087/69658840-9ad8b200-1042-11ea-8e18-c88855118984.png">

**Comment by jkodu** [comment]
@amberleyromo 

Thanks for reporting. 

I have just tested this on a [gatsbyjs](https://www.gatsbyjs.org/) website & unfortunately I am not able to replicate this issue.

The website I tested this on is [ACT Rules](https://act-rules.github.io/) & in this case this uses `react-helmet` for setting the `title`, see - https://github.com/act-rules/act-rules-web/blob/master/src/components/seo.js#L46

I have a feeling this is not a hydration issue. Do you have a custom `html.js` perhaps?

Are you able to provide a sample repository where this can be replicated? To enable me to assist further?

**Comment by jkodu** [comment]
@amberleyromo I also checked this repo locally - https://github.com/cityofaustin/census2020 & did not find the title issue.

**Comment by amberleyromo** [comment]
Hi @jkodu! Here's an animated gif of running it. I didn't see it on initially opening the dev site, but after refreshing it.

![false-positives](https://user-images.githubusercontent.com/3461087/69881266-12e8e700-1292-11ea-8c6b-f603b98dc37d.gif)

**Comment by amberleyromo** [comment]
@jkodu I've chatted with the team, it does look like it might be an issue with Gatsby's rehydration. I'll let you know what we track down.

**Comment by pieh** [comment]
Ok, so few notes from Gatsby side:

The `react-axe` integration is done via plugin ( https://github.com/angeloashmore/gatsby-plugin-react-axe/blob/master/src/gatsby-browser.js ), which hooks into very first extension point possible to "run" `react-axe`. 

This hook executes before react app is mounted. It sets `timeout` to 1s, but this is timeout for `requestIdleCallback`, and we can get those before app is mounted because of fetching/loading of additional resources that gatsby does.

Ideally for Gatsby, `react-axe` would allow to setup `react` spies ( https://github.com/dequelabs/react-axe/blob/develop/index.js#L259-L273) and audit execution in 2 separate methods, so we could mutate `react` module early, but execute audit itself later on when we know that app is mounted.

**Comment by pieh** [comment]
Alternatively, maybe `react-axe` could spy on `react-dom` `render` as well and wait for this to be called (within specified `timeout`) before running `axe` audit?

**Comment by jkodu** [comment]
@amberleyromo 

I tried your steps suggested here - https://github.com/dequelabs/react-axe/issues/124#issuecomment-559837459 and below is what I found. Refreshed a few times and the `title` violation does not show up. Are you in a different branch perhaps, where this issue could have manifested itself?

![census](https://user-images.githubusercontent.com/20978252/69968680-d37cfd80-1512-11ea-97a6-879a886345b9.gif)

@pieh Thanks for your suggestions as well.

----

I debugged through the plugin and having read up the Gatsby browser API, perhaps [onInitialClientRender](https://www.gatsbyjs.org/docs/browser-apis/#onInitialClientRender) would be a good hook for wiring up [react axe](https://github.com/dequelabs/react-axe/).

I went ahead and forked the plugin and updated the `census2020` to use the plugin which used `onInitialClientRender`. The change in question is https://github.com/cityofaustin/census2020/compare/master...jkodu:react-axe-plugin-onInitialClientRender?expand=1#diff-ddbc9fdc5a774b2fa448bd2ec562c9b1R29

The issue does not seem to re-occur in this branch. Do you mind giving it a try on your end?

**Comment by amberleyromo** [comment]
@jkodu thanks! Yes, this issue was on master. I'm not sure how it's not occurring for you. @pieh also suggested hooking into `onInitialClientRender` instead of `onClientEntry`, I certainly agree that makes more sense.

I've PR'd the tweak to [the plugin repo](https://github.com/angeloashmore/gatsby-plugin-react-axe/pull/1) and in the meantime, [PR'd a change to the project repo](https://github.com/cityofaustin/census2020/pull/54) that pulls the audit out of the plugin and into the project's `gatsby-browser` file directly instead.

Thanks again!

**Comment by angeloashmore** [comment]
Thanks @amberleyromo for the PR. I merged in and published the change as `v0.3.0`.

https://www.npmjs.com/package/gatsby-plugin-react-axe/v/0.3.0

**Comment by jkodu** [comment]
@amberleyromo Excellent stuff. Thanks.
