### ISSUE TITLE
Error - Uncaught (in promise) Axe is already running. Use `await axe.run()` 

### ISSUE THREAD

**Issue by golgistudio** [dequelabs/react-axe#132]
Seeing the following error in chrome dev tools for a collapse control.  It is slowing down the performance of running our application.

"Uncaught (in promise) Axe is already running. Use `await axe.run()` to wait for the previous run to finish before starting a new run."

System:  MacOS
Browser: Chrome
Version of react-axe - 3.3.0

We initialize it as described in the README

**Comment by straker** [comment]
This error happens when `axe` is currently running and is asked to run again. The 3rd parameter of react-axe is a debounce timer that should help prevent multiple runs of axe in a row. You could try increase it from `1000` to something higher if the collapse control changes state often.

**Comment by padmavemulapati** [comment]
Unable to execute react-axe, because of an update of chrome. Making the tiket work in progress and will verify once issue fixed.

**Comment by padmavemulapati** [comment]
With debounce time, react-axe's axe.run is wating for the timeout.. and not throwing any exceptions. Working as expected.

**Comment by golgistudio** [comment]
Thank you!   Will check once this issue is resolved.

https://github.com/dequelabs/react-axe/issues/144
