### ISSUE TITLE
Don't execute until trigger/delay

### ISSUE THREAD

**Issue by reintroducing** [dequelabs/react-axe#134]
I was under the impression that if I did this: `axe(React, ReactDOM, 5000);` axe wont execute until 5 seconds in. I'm basically trying to delay execution because axe is running before my page (with API calls) fully renders and I'm seeing issues that don't really exist once the API calls are finished and I render the page successfully with all elements. Am I misunderstanding that third parameter? How can I delay execution until a certain time (or ideally, it would plug in to some kind of event that I can fire and only execute then, but that may be out of the scope of this package)?

**Comment by straker** [comment]
I believe the 3rd parameter is a debounce delay that prevents multiple updates of the component from triggering multiple axe calls. So it won't wait 5 seconds to start analyzing. You'll probably need to wait for the API calls to settle before you initialize `axe` on the page.

**Comment by reintroducing** [comment]
@straker Got it, so that would work for initial page load, but how about when navigating around the site? subsequent pages also load APIs and axe is evaluating the loading state of the pages before the API calls come back.

**Comment by straker** [comment]
Excellent question. I'm not sure on that one. I'll try to find an answer and get back to you

**Comment by reintroducing** [comment]
Really appreciate your quick responses and help on this.

**Comment by jzaefferer** [comment]
@straker did you find an answer for this? It looks like we're running into the same issue.

**Comment by straker** [comment]
I have not yet. We're preparing for a few huge releases and haven't been able to get to this yet. I'll try to bring this up again after the releases go out.

**Comment by jkliptonia** [comment]
This would be incredibly helpful, I'm struggling with issues with fade-ins and waiting on rendering components.

**Comment by straker** [comment]
We have moved this package to be under our [axe-core-npm](https://github.com/dequelabs/axe-core-npm/) monorepo for easier management. As a result, this repository will be deprecated in the coming weeks. 

I have [transferred the issue](https://github.com/dequelabs/axe-core-npm/issues/92) so we can still keep track of it.
