### ISSUE TITLE
Add license file? 

### ISSUE THREAD

**Issue by Robdel12** [dequelabs/react-axe#14]
Hi Deque team! 

~~What is the license that this package is released under?~~

Edit: found it's MPL-2.0 https://github.com/dequelabs/react-axe/blob/master/package.json#L26 I'll rename this to add a license file :)

**Comment by dylanb** [comment]
Mozilla Public License 2.0 - look at the package.json file

**Comment by Robdel12** [comment]
I did, would it be possible to add a file too? I can't use packages without it sadly.

**Comment by dylanb** [comment]
License file added

**Comment by Robdel12** [comment]
Thank you!! :D
