### ISSUE TITLE
Project broken after latest release

### ISSUE THREAD

**Issue by wmacdonald919** [dequelabs/react-axe#153]
With the update to typescript, and this being released under a minor version `3.5.0` has caused our project to break when developing locally. I feel this should have been released under a major due to the breaking nature of the change with no backwards compatibility?

We are not using typescript and therefore our project is not set up for typescript which meant when importing `react-axe`, it was looking for the now deleted `index.js`. 

I appreciate all the work you guys do and understand keeping a project going that is so widely used in the industry is a lot to take on. Please don't take this as an angry dev asking for the world 🍻 . Just a bit of a frustrating morning. 
Forcing to `3.3.0` resolved this.

**Comment by straker** [comment]
Apologies for the broken release. We are looking into it. It appears [npm did not publish](https://unpkg.com/browse/react-axe@3.5.0/) the needed compiled file `dist/index.js` and `dist/after.js` even though running `npm publish --dry-run` includes those files in the tarball.

![image](https://user-images.githubusercontent.com/2433219/85145723-3feaf000-b20a-11ea-99fe-5d3ba67964f6.png)

**Comment by wmacdonald919** [comment]
Gotcha, ya I noticed in your examples it was still referring to a `dist` folder but thought maybe those just weren't updated yet.

Thank you for the quick response, really appreciate everything you guys are doing, and I understand the fun of build pipelines and NPM

Cheers

**Comment by m4thieulavoie** [comment]
> Apologies for the broken release. We are looking into it. It appears [npm did not publish](https://unpkg.com/browse/react-axe@3.5.0/) the needed compiled file `dist/index.js` and `dist/after.js` even though running `npm publish --dry-run` includes those files in the tarball. We'll get a fix out as soon as we can and publish as 5.1.
> 
> ![image](https://user-images.githubusercontent.com/2433219/85145723-3feaf000-b20a-11ea-99fe-5d3ba67964f6.png)

I think this PR might fix it https://github.com/dequelabs/react-axe/pull/152

As per https://docs.npmjs.com/files/package.json , 
```
The optional files field is an array of file patterns that describes the entries to be included when your package is installed as a dependency
```

**Comment by straker** [comment]
Alright. After fighting circle all morning, we have a release of 3.5.2 that should be stable once again with the required `dist` complied files available.

**Comment by wmacdonald919** [comment]
Just ran a fresh install and the `dist` is there. Cheers guys, I know its a battle sometimes with build pipelines, seen it first hand.
