### ISSUE TITLE
TypeScript types are wrong

### ISSUE THREAD

**Issue by danielnixon** [dequelabs/react-axe#170]
This no longer compiles.

```typescript
axe(React, ReactDOM, 1000);
```

```
Expected 5 arguments, but got 3.ts(2554)
index.d.ts(12, 95): An argument for 'conf' was not provided.
```

The fourth and fifth arguments should be optional.

**Comment by m4thieulavoie** [comment]
Having the same issue, I just opened a PR for this https://github.com/dequelabs/react-axe/pull/171 , hopefully it can ship quickly! 👍

**Comment by m4thieulavoie** [comment]
@straker think we can cut a release for this?

**Comment by straker** [comment]
Yep. Will hopefully get out a release today.

**Comment by straker** [comment]
Alright. 3.5.3 released and should fix the problem. Thank you for your help and patience.
