### ISSUE TITLE
Ignore axe/3.5/region by default

### ISSUE THREAD

**Issue by AdrienLemaire** [dequelabs/react-axe#182]
After setting up react-axe, I got this error: [All page content must be contained by landmarks](https://dequeuniversity.com/rules/axe/3.5/region).

Given that we use react, which must have a root div element, shouldn't this error be ignored by default ?
This [SO answer](https://stackoverflow.com/questions/63935142/how-can-we-fix-the-a11y-error-all-page-content-must-be-contained-by-landmarks/63935602#63935602) gives more info about why it's safe to ignore it.

**Comment by straker** [comment]
Interesting. I'm not seeing that problem using the example in react-axe (adding a `<main>` element around the `<ServiceChooser>` removes the error, as is expected). Axe-core should only flag actual text content with that error and not elements. You should be able to wrap the landmarks with any amount of divs.

![image](https://user-images.githubusercontent.com/2433219/93609606-4ca5ee00-f989-11ea-80d2-94b5997a7bc8.png)

**Comment by straker** [comment]
We have moved this package to be under our [axe-core-npm](https://github.com/dequelabs/axe-core-npm/) monorepo for easier management. As a result, this repository will be deprecated in the coming weeks. 

I have [transferred the issue](https://github.com/dequelabs/axe-core-npm/issues/92) so we can still keep track of it.
