### ISSUE TITLE
axe issues thrown when there are no issues

### ISSUE THREAD

**Issue by AdrienLemaire** [dequelabs/react-axe#183]
![](https://i.imgur.com/h9ZOjEf.png)

As you can see, the issues are toggled but no link to the code is given below them.

I've also verified that I do have only 1 `<main>` element and only one `<h1>` within it

![](https://i.imgur.com/2X0TPxk.png)

versions used:
```json
{
    "react-axe": "^3.5.3",
    "react": "0.0.0-experimental-94c0244ba",
    "react-dom": "0.0.0-experimental-94c0244ba"
}
```

**Comment by straker** [comment]
Out of curiosity, are these issues being thrown as the page is loaded (this and the other issue you posted? I'm wondering if the DOM is not yet populated with react DOM when axe throws the errors

**Comment by AdrienLemaire** [comment]
@straker you might be right. Axe errors are thrown very quickly, and adding a slow debouncing eg 5000 doesn't seem to have any effect.
Wondering if it's a react concurrent only issue

**Comment by straker** [comment]
Ya, debounce wouldn't help for initial loading before the page is ready. I know #134 also had that problem and it's something we're trying to look into.

**Comment by straker** [comment]
We have moved this package to be under our [axe-core-npm](https://github.com/dequelabs/axe-core-npm/) monorepo for easier management. As a result, this repository will be deprecated in the coming weeks. 

I have [transferred the issue](https://github.com/dequelabs/axe-core-npm/issues/92) so we can still keep track of it.
