### ISSUE TITLE
findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by Nick-Mazuk** [dequelabs/react-axe#184]
As soon as I hooked up react-axe, I got dozens of instances of this error:

```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of [function component] which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
```

Where `[function component]` is the display name of a function component used on the current page.

I am using Next JS and integrated `react-axe` as shown in  https://github.com/dequelabs/react-axe/issues/125

```jsx
// _app.tsx

if (process.env.NODE_ENV !== 'production' && typeof window !== 'undefined') {
    const axe = require('react-axe')
    const ReactDOM = require('react-dom')
    axe(React, ReactDOM, 5000)
}
```

The errors are almost certainly coming from `react-axe` since the following does not produce any errors:

```jsx
// _app.tsx

if (process.env.NODE_ENV !== 'production' && typeof window !== 'undefined') {
    const axe = require('react-axe')
    const ReactDOM = require('react-dom')
    // axe(React, ReactDOM, 5000)
}
```

Any ideas on how to fix this? It looks like `react-axe` is correctly identifying accessibility errors, but those errors are drowned by seas of this error making the use of `react-axe` impractical right now.

**Comment by straker** [comment]
Ya, `findDOMNode` is deprecated, but the correct way to replace it is to use the `ref` attribute, which we don't have access to. So for now we use it but don't have a fix other than don't use strict mode.

**Comment by straker** [comment]
We have moved this package to be under our [axe-core-npm](https://github.com/dequelabs/axe-core-npm/) monorepo for easier management. As a result, this repository will be deprecated in the coming weeks. 

I have [transferred the issue](https://github.com/dequelabs/axe-core-npm/issues/94) so we can still keep track of it.

**Comment by Nick-Mazuk** [comment]
Ok, thanks Straker!
