### ISSUE TITLE
"Too much recursion" and slowdown in Firefox.

### ISSUE THREAD

**Issue by AlmeroSteyn** [dequelabs/react-axe#21]
I previously logged the same issue which I promptly closed after seeing that `react-axe` is only really supported in Chrome. However this issue is now starting to prevent me from using `react-axe` in some projects.

In some cases I get the following in Firefox browser (latest Windows version):
![image](https://user-images.githubusercontent.com/5063473/30047367-150fa11c-9211-11e7-901c-503b4a5b51d4.png)

It also then severely degrades performance when the dev tools is open.

Before resorting to nasty browser detection things, is there a known way to stop this from happening? 

Would really love to use this everywhere because it is awesome!

**Comment by apobbati** [comment]
Were you able to workaround this issue?

**Comment by AlmeroSteyn** [comment]
@apobbati now that you mention it I haven’t seen it for a while. Upgraded to the latest version and running the new Firefox. One of those seemed to fix this. Sorry kind of forgot the issue was open.
