### ISSUE TITLE
react-axe no longer works with React 16+

### ISSUE THREAD

**Issue by majornista** [dequelabs/react-axe#26]
With React 16+, while react-axe still seems to execute following timeout on page load, the hooks to check accessibility after `componentDidMount` or `componentDidUpdate` no longer seem to execute.

Adding breakpoint at: https://github.com/dequelabs/react-axe/blob/b9b45d99636b6df5071b7dd062492e3c5c83897b/index.js#L193 shows that `reactEl._owner._instance` does not exist.

**Comment by WilcoFiers** [comment]
@majornista Are you interested in working on a fix for this? I'm afraid we currently don't have the band with to do so.

**Comment by majornista** [comment]
I may have to if that's the only way it can get fixed. :\

**Comment by marcysutton** [comment]
I'm taking a look at it now with the upgrade for Shadow DOM.

**Comment by badtant** [comment]
time to release 3.0.0?

**Comment by WilcoFiers** [comment]
@badtant We got a little preoccupied with CSUN conference, but it's out as of yesterday.
