### ISSUE TITLE
Expect axe._selectorData to be set up

### ISSUE THREAD

**Issue by badtant** [dequelabs/react-axe#32]
Don't know if this is because of axe-core or react-axe

![screen shot 2018-04-04 at 12 51 33](https://user-images.githubusercontent.com/400265/38303689-0816d808-3807-11e8-9db1-a225b7505307.png)

**Comment by WilcoFiers** [comment]
That's axe. What version are you using? Can you provide steps to reproduce?

**Comment by badtant** [comment]
react-axe 3.0.0 and axe-core 3.0.1
reactAxe(React, ReactDOM)

I'm using webpack-dev-server

**Comment by dylanb** [comment]
@WilcoFiers This change broke the debouncing, which also means that there are multiple calls happening at the same time. We need to back this out

https://github.com/dequelabs/react-axe/commit/1d4bd8db521d38f4fba831e3066339dc21d31325

**Comment by dylanb** [comment]
Also, until we do this, we should unpublish 3.0.0 (or at least make 2.9.1 the current

**Comment by dylanb** [comment]
@stephenmathieson I have an application where I can reproduce this consistently https://github.com/dequelabs/color-palette just upgrade react-axe to 3.0.0

**Comment by dylanb** [comment]
@WilcoFiers we can designate which version is @next and which is current, I strongly suggest we do this as this is hurting this module because it will be broken for everyone who tries it

**Comment by stephenmathieson** [comment]
I should be able to take a look at this today.

**Comment by stephenmathieson** [comment]
@dylanb I've made the following change to your color-palette app:

```diff
diff --git a/package.json b/package.json
index fa8bfb4..3ee82af 100644
--- a/package.json
+++ b/package.json
@@ -21,7 +21,7 @@
   "devDependencies": {
     "a11y-color": "0.0.8",
     "hex-rgb": "^2.0.0",
-    "react-axe": "^2.1.9",
+    "react-axe": "^3.0.0",
     "rgb-hex": "^2.1.0"
   }
 }
```

and it still runs fine. Do you have any other reproduction steps?

**Comment by stephenmathieson** [comment]
@badtant We have fixed the bug and will create a release for this ASAP. In the mean time, if this is blocking, you can install this package right from GitHub:

```
$ npm install dequelabs/react-axe
```
