### ISSUE TITLE
Not possible to exclude nodes?

### ISSUE THREAD

**Issue by rdewit-bom** [dequelabs/react-axe#41]
There appears to be no way to exclude nodes from being checked by react-axe. I'd like to be able to exclude a 3rd party div that I have no control over (hotjar in this case).

The include/exclude options are part of the context parameter that gets passed into the run method of axe-core but in react-axe changing that setting appears not to be possible.

Is there another way of achieving this or would a change in the library be needed?

**Comment by marcysutton** [comment]
A change would be needed, as the code walks the node tree without taking include/exclude into account. cc @dylanb

**Comment by dylanb** [comment]
Perhaps we could add a callback that receives a node and returns true/false depending on whether it should be tested?

**Comment by J-Kallunki** [comment]
https://github.com/dequelabs/axe-core/blob/develop/doc/API.md#context-parameter-examples

**Comment by liranko** [comment]
The include/exclude from the link @J-Kallunki attached does not seem to be working..
Is there another way to use axe-core context params in react-axe?

**Comment by clottman** [comment]
Seconding this - I need a way to exclude iframes at least if this is going to be useful on the site I work on. As is, I get `Error: No response from frame` anyways so I'm not even getting the iframe's errors, which I can't control any ways.

**Comment by tombartlettmh** [comment]
> https://github.com/dequelabs/axe-core/blob/develop/doc/API.md#context-parameter-examples

Looks like this wouldn't be possible at the moment, as react-axe doesn't use any passed config in the `axeCore.run` call ... the second argument is hard-coded to set the reporter. 

```
axeCore.run(n, { reporter: 'v2' }, function(error, results) { ...
```

Perhaps you could pass another object down to set this? 

https://github.com/dequelabs/react-axe/blob/develop/index.js#L135

**Comment by J-Kallunki** [comment]
Hi again. I created PR that with manual testing seems to working at least with simple case.
Please see #127 to get it implemented properly and hopefully released.

**Comment by straker** [comment]
@J-Kallunki changes have been released under react-axe 3.4.0.

**Comment by padmavemulapati** [comment]
Unable to execute react-axe, because of an update of chrome. Making the tiket work in progress and will verify once issue fixed.

**Comment by padmavemulapati** [comment]
Verified with the latest react-axe, it is excluding nodes . Looking the results as per expectations.
Before excluding the nodes, it has color-contrast issues, and after excluding the node "#service-choose" below is the result. (it is excluding color-contrast issues)
![image (13)](https://user-images.githubusercontent.com/47409579/77031395-850f4400-69c7-11ea-9f7f-599d6d17f3cf.png)
![image (12)](https://user-images.githubusercontent.com/47409579/77031399-86407100-69c7-11ea-9997-1628734cc8fb.png)
![image (11)](https://user-images.githubusercontent.com/47409579/77031402-86d90780-69c7-11ea-8a5f-ee4eb2cabfa4.png)
![image (10)](https://user-images.githubusercontent.com/47409579/77031404-880a3480-69c7-11ea-8079-d0aa8effbed3.png)
![20200316_180450](https://user-images.githubusercontent.com/47409579/77031406-880a3480-69c7-11ea-8463-202386c05304.gif)
