### ISSUE TITLE
Question: My project based on static(single server-side) rendering. 

### ISSUE THREAD

**Issue by JustFly1984** [dequelabs/react-axe#43]
Is it strict requirement to add DOMContentLoaded event listener?

My app uses react-static build tool for static rendering. It has dev mode similar with create-react-app, with HMR.

I'm using eslint with a11y plugin, and wanted to try your tool, but I'm not sure if I want to bundle your tool with everything else in production.

**Comment by WilcoFiers** [comment]
The best way to use this is to only bundle it in your dev environment. The readme explains how to do this. Most bundlers will respect this and so they'll exclude react-axe for your production:

https://github.com/dequelabs/react-axe#initialize-the-module
