### ISSUE TITLE
EvalError: Refused to evaluate a string as JavaScript 

### ISSUE THREAD

**Issue by lhorie** [dequelabs/react-axe#54]
React-axe doesn't work when loaded in a page with strict content security policies (e.g. it throws EvalError if e.g. script-src 'self')

Link to live demo: https://github.com/lhorie/axe-csp-bug

```
react-axe version: 3.0.2
axe-core version: 3.0.0
```

One workaround is to disable CSP rules in development, but ideally, CSP rules should be the same in dev and prod to avoid crashes if an unrelated package also abuses eval-like constructs

Here's where the code throws:

```js
// node_modules/axe-core/axe.js:1755
  'use strict';
  axe.imports['doT'] = function(module, exports, define, require, process) {
    var global = Function('return this')(); // <---
```

I assumed it had something to do with this: https://github.com/dequelabs/axe-core/blob/ae2e09377cadb0c3229c8cc33497d8a81bf828d2/Gruntfile.js#L154

The `react-axe` package does not explicitly depend on `doT`

I also found other instances, e.g.

```js
// node_modules/axe-core/axe.js:243
metadata.messages[prop] = new Function('return ' + metadata.messages[prop] + ';')();
```

which presumably comes from https://github.com/dequelabs/axe-core/blob/6bfff2b9d2d7b7868df5fd7fe026d284a96787fb/lib/core/base/audit.js#L306

This issue is a dupe of https://github.com/dequelabs/axe-core/issues/1158 filed here at the request of @WilcoFiers

**Comment by drewlee** [comment]
@lhorie, you may be interested in https://github.com/dequelabs/axe-core/issues/1175. As far as I can tell, the issue has nothing to do with react-axe. It's coming from the doT library that axe-core is using as a dependency and is a known issue https://github.com/olado/doT/issues/276.

**Comment by lhorie** [comment]
Yes, that's the conclusion I arrived at. I originally filed this issue at axe-core, but @WilcoFiers asked me to re-file here.

FWIW, doT is not the only place where eval-likes are being used (e.g. see the snippet from audit.js in the comment above)

**Comment by straker** [comment]
Work has been done in axe-core to remove doT.js and other strict CSP issues. These changes went into axe-core 3.5.0 which was updated for the react-axe 3.4.0 release that just went out. Closing as this work will continue to be tracked in axe-core.

**Comment by malveujvala** [comment]
Hi... I am also facing the same issue with the Axe-core integration with Java.  Currently, I am using the below dependency in POM.xml file 

	<dependency>
			<groupId>com.deque</groupId>
			<artifactId>axe-selenium</artifactId>
			<version>3.0</version>
		</dependency>

Any plan to fix this issue with Java integration as well? I can't update the dependency to 3.5. Any workaround which I can use to fix the issue. Please let me know. I am currently blocked due to this.
