### ISSUE TITLE
level of conformity

### ISSUE THREAD

**Issue by dalefrancis88** [dequelabs/react-axe#64]
Hey, I'm sure this is somewhere but i just can't find it, sorry if it's somewhere obvious. 

What level on conformity does this ensure you hit if the application runs and there are no warnings?

https://www.w3.org/WAI/WCAG2AAA-Conformance

**Comment by georgewilde** [comment]
I was also wondering this. Is there a way of specifying the level of conformance you want to achieve? For example, I may want to only run tests tagged with "wcag2a".

**Comment by dalefrancis88** [comment]
I'm guessing that for whatever odd reasone @dequelabs appears to be ignoring this. Closing

**Comment by straker** [comment]
Automated accessibility tools can only detect roughly 30% of accessibility errors. Because of this, you cannot ensure any level of conformance using only automated accessibility testing. Manual testing of the site for the desired conformance level is required to claim a level of conformity.

**Comment by ahahn95** [comment]
Is there any way to ignore errors or anything if you cannot set the compliance level? For instance, I have a contrast error because it is not in level AAA compliance, but I only care for level AA.
