### ISSUE TITLE
React-Axe with React Native

### ISSUE THREAD

**Issue by us-and-them** [dequelabs/react-axe#66]
Is react-axe compatible with react native? Or does anyone know a way to make it work with react native application?

**Comment by Michael-M-Judd** [comment]
I think axe was purpose-built for the web. Unfortunately the "react" portion of this is specifically for ReactDOM. Maybe this is something on the roadmap far far from now?

**Comment by straker** [comment]
Unfortunately, we don't have any plans to support React Native. 

As and FYI, we have moved this package to be under our [axe-core-npm](https://github.com/dequelabs/axe-core-npm/) monorepo for easier management. As a result, this repository will be deprecated in the coming weeks.
