### ISSUE TITLE
Setup canary releases

### ISSUE THREAD

**Issue by stephenmathieson** [dequelabs/react-axe#67]
All commits that land in `develop` should be released as a `@next` dist tag using the Git SHA in the version, similar to what we do in [axe-core](https://github.com/dequelabs/axe-core/blob/develop/.circleci/config.yml#L61-L68) and [axe-puppeteer](https://github.com/dequelabs/axe-puppeteer/blob/develop/.circleci/config.yml#L40-L49).

**Comment by straker** [comment]
Done in https://github.com/dequelabs/react-axe/pull/156
