### ISSUE TITLE
Add TypeScript declaration file

### ISSUE THREAD

**Issue by danielnixon** [dequelabs/react-axe#73]
Please add a TypeScript declaration file.

See https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html

**Comment by danielnixon** [comment]
Below is what I'm using at the moment. It might be a good starting point.

```
declare module "react-axe" {
  // TODO: strongly typed config object https://github.com/dequelabs/axe-core/blob/master/doc/API.md#api-name-axeconfigure
  declare function axe(react: typeof React, reactDOM: typeof ReactDOM, timeout: number, config?: {}): void;
  
  export = axe;
}
```

**Comment by stephenmathieson** [comment]
I'm of the opinion we should either add types to the DefinatelyTyped project, or rewrite this package in TS. Maintaining TS defs in a JS repo is tedious and error-prone.

**Comment by akshaykarthik** [comment]
I've added a react-axe file to definitelytyped in this MR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34108

**Comment by stephenmathieson** [comment]
Awesome, thanks @akshaykarthik
