### ISSUE TITLE
Problem with lazy routes

### ISSUE THREAD

**Issue by dbenfouzari** [dequelabs/react-axe#74]
Hi

I can't get react-axe working with React.lazy imports.

Here is my react-axe related code
```js
if (process.env.NODE_ENV !== 'production') {
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const axe = require('react-axe');
  axe(React, ReactDOM, 5000); // big delay here because I want it to check a11y after lazy load
}
```

and here is my Routes' related code 
```jsx
import React from 'react';
import { Route, Switch } from 'react-router';

const Home = React.lazy(() => import(/* webpackChunkName: "Home" */ './Home'));
const NotFound = React.lazy(() =>
  import(/* webpackChunkName: "NotFound" */ './NotFound'),
);

const LoadingComponent = () => <div>Loading...</div>;

const Routes = (): JSX.Element => (
  <React.Suspense fallback={<LoadingComponent />}>
    <Switch>
      <Route exact path='/' component={Home} />
      <Route component={NotFound} />
    </Switch>
  </React.Suspense>
);

export default Routes;
```

When I reload the page, it works correctly, but after following a `Link` it throws an error `Invariant Violation: Unable to find node on an unmounted component`

I thought it was a React-Router related error, but after removing `axe` it works just fine.

Any help ?

**Versions** :
* react-axe@3.1.0
* react@16.8.5
* react-dom@16.8.5

Thanks

**Comment by frankcalise** [comment]
I'm experiencing this also.

- react-axe@3.1.0
- react@16.8.6
- react-dom@16.8.6

**Comment by erin-doyle** [comment]
I can't seem to filter out these errors using any of the Chrome Dev Tools filter capabilities either.  Maybe I'm doing something wrong but it seems like no matter what I try these errors are always showing.  If there was some way to filter these out in the meantime that would be great!  I really don't want to have to stop using this library but as it is now we're getting more noise from these errors than we can comb through.

**Comment by katy6514** [comment]
Also having these issues, the "aXe error: could not check node" errors are overwhelming the console, and would like to be able to see just the (serious/critical/moderate/etc..) issues we can fix

**Comment by katy6514** [comment]
Update: The original version of react-axe I had installed was 3.4.1, lowering it down to 3.3.0 resolved this issue.

**Comment by straker** [comment]
I'm guessing this is a problem with how React-axe determines when to run (immediately) instead of waiting for things to load.

We have moved this package to be under our [axe-core-npm](https://github.com/dequelabs/axe-core-npm/) monorepo for easier management. As a result, this repository will be deprecated in the coming weeks. 

I have [transferred the issue](https://github.com/dequelabs/axe-core-npm/issues/92) so we can still keep track of it.
