### ISSUE TITLE
feature request: add support for runOnly

### ISSUE THREAD

**Issue by jamime** [dequelabs/react-axe#75]
Currently react-axe does not allow you to configure the run command, only axe.configure. axe.configure does not support runOnly.

I currently have this code
```js
reactAxe(React, ReactDOM, 1000, {
      rules: AxeCore.getRules(['wcag2aa', 'wcag2a']).map(rule => ({...rule, id: rule.ruleId, enabled: true})),
      disableOtherRules: true
    });
```
but I think the following would be preferable. 
```js
reactAxe(React, ReactDOM, 1000, {
      runOnly: ['wcag2aa', 'wcag2a']
    });
```

**Comment by jeannnemelanie** [comment]
+1

**Comment by straker** [comment]
We have moved this package to be under our [axe-core-npm](https://github.com/dequelabs/axe-core-npm/) monorepo for easier management. As a result, this repository will be deprecated in the coming weeks. 

I have [transferred the issue](https://github.com/dequelabs/axe-core-npm/issues/93) so we can still keep track of it.

**Comment by zwbetz-gh** [comment]
link https://github.com/dequelabs/axe-core-npm/ seems to be broken
